{% set version = "2.0.0" %}

package:
  name: runiq
  version: {{ version }}

source:
  url: https://github.com/whitfin/runiq/archive/v{{ version }}.tar.gz
  sha256: 99e5f9fa7389608cabad1fc8cb640739e48a28f02462a2db7a56d0c12138266e

build:
  number: 0

requirements:
  build:
    - {{ compiler("rust") }}
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - runiq --help

about:
  home: https://github.com/whitfin/runiq
  dev_url: https://github.com/whitfin/runiq
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An efficient way to filter duplicate lines from input, à la uniq

extra:
  recipe-maintainers:
    - apcamargo
